# Generated by Django 5.0.6 on 2024-05-21 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netbox',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='netbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
