# Generated by Django 5.0.6 on 2024-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0003_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='sites',
            field=models.CharField(default='default-site', max_length=100),
        ),
        migrations.AlterField(
            model_name='netbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
