# Generated by Django 5.0.6 on 2024-05-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0004_pod_sites_alter_netbox_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pod',
        ),
    ]
