# Generated by Django 5.0.6 on 2024-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0005_delete_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='netbox',
            name='pod_count',
            field=models.IntegerField(null=True),
        ),
    ]
