# Generated by Django 5.0.6 on 2024-05-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0006_netbox_pod_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netbox',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='netbox',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
