# Generated by Django 5.0.6 on 2024-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0008_pod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pod',
        ),
    ]
