# Generated by Django 5.0.6 on 2024-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_netbox', '0009_delete_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='netbox',
            name='pods',
            field=models.JSONField(null=True),
        ),
    ]
